export { default as Menu } from "./Menu/Menu"
export { default as Home } from "./Home/Home"
export { default as Header } from "./Header/Header"
export { default as Navbar } from "./Navbar/Navbar"
export { default as Contact } from "./Contact/Contact"
